apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: enterprise-idp-platform
  title: Enterprise Internal Developer Platform
  description: >
    An enterprise Internal Developer Platform built using Backstage,
    Azure Kubernetes Service, Terraform, GitHub Actions, Azure DevOps,
    Azure Container Registry and Azure Key Vault.

  annotations:
    github.com/project-slug: luckysuie/enterprise-idp-platform
    backstage.io/techdocs-ref: dir:.

  tags:
    - backstage
    - azure
    - aks
    - terraform
    - github-actions
    - azure-devops
    - idp

spec:
  type: platform
  lifecycle: experimental
  owner: guests
  system: enterprise-idp
