# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: luckyashu1856
spec:
  profile:
    displayName: Lucky Ashu
    email: luckyashu1856@gmail.com
  memberOf: [guests]
